### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by imbdan01** [josh0xA/Scylla#1]
# python3 --version
Python 3.6.9

I tried to run : 
# python3 setup.py install
  File "setup.py", line 16
    console =['scylla.py'],
          ^
SyntaxError: invalid syntax

**Comment by Nret** [comment]
A comma is missing on the line above.

    install_requires = ['termcolor','requests','urllib3', 'urllib', 'pythonwhois', 
    'BeautifulSoup4', 'google', 're', 'json', 'contextlib']
    console =['scylla.py'],
)

the argument before console is missing the command
should be

    install_requires = ['termcolor','requests','urllib3', 'urllib', 'pythonwhois', 
    'BeautifulSoup4', 'google', 're', 'json', 'contextlib'], # << This comma
    console =['scylla.py'],
)

**Comment by josh0xA** [comment]
The setup.py script has been fixed. You can now install it properly.

**Comment by imbdan01** [comment]
Ok thanks !
