### ISSUE TITLE
(Personal Issue)Permission Denied when trying to install

### ISSUE THREAD

**Issue by XtraMayo1775** [josh0xA/Scylla#6]
Very new to Git and Github
When attempting to install Scylla via Git Bash i keep getting Permission Denied at install requirements.txt step. 
Any advice?

**Comment by josh0xA** [comment]
Type ``sudo python3 -m pip install -r requirments.txt`` 

Then type in your password. It should install just fine because sudo allows you to become essentially an administrator on Linux.

**Comment by XtraMayo1775** [comment]
Is it only compatible with Linux?
Shows how much I know. I've been trying to get it to run with Windows 10. I
guess I will have to run Linux as well
